spring:
  profiles:
    active:
    - dev

---
server:
  port: 8201
spring:
    profiles: dev
    application:
          name: chtpro-config-haite-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka_dev.com:7001/eureka/

---
server:
  port: 8202
spring:
    profiles: test
    application:
          name: chtpro-config-haite-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka_test.com:7001/eureka/