spring:
  profiles:
    active:
    - dev

---
server:
  port: 8001
spring:
    profiles: dev
    application:
          name: chtpro_config_dept_client

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.haite.chtpro.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: chtpro-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3380/chtpro8001
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
       #defaultZone: http://localhost:7001/eureka/
        defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: chtpro-dept8001
    prefer-ip-address: true

info:
  app.name: haite-microservicecloud
  company.name: www.haite.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
    profiles: test
    application:
          name: chtpro_config_dept_client

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.haite.chtpro.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: chtpro-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3380/chtpro8002              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
       #defaultZone: http://localhost:7001/eureka/
        defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: chtpro-dept8001
    prefer-ip-address: true

info:
  app.name: haite-microservicecloud
  company.name: www.haite.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$